drop table if exists stats cascade;

create table if not exists stats (
    id BIGINT generated by default as identity primary key not null,
    app VARCHAR not null,
    uri VARCHAR not null,
    ip VARCHAR not null,
    timestamp TIMESTAMP WITH TIME ZONE not null


);