drop table if exists users cascade;
drop table if exists events cascade;
drop table if exists categorys cascade;
drop table if exists requests cascade;

create table if not exists users
(
    id    BIGINT generated by default as identity primary key,
    name  VARCHAR not null,
    email VARCHAR not null unique
);

create table if not exists categorys
(
    id   BIGINT generated by default as identity primary key,
    name VARCHAR
);

create table if not exists events
(
    id                 BIGINT generated by default as identity primary key,
    title              VARCHAR(120)  not null,
    annotation         VARCHAR(2000) not null,
    category_id        BIGINT references categorys,
    description        VARCHAR(7000) not null,
    event_date         TIMESTAMP without time zone,
    location_lat       float4,
    location_lon       float4,
    paid               boolean,
    participantLimit   INT,
    created_on         TIMESTAMP without time zone,
    initiator_id       BIGINT references users,
    published_on       TIMESTAMP without time zone,
    request_moderation boolean,
    state              VARCHAR
);



create table if not exists requests
(
    id           BIGINT generated by default as identity primary key,
    event_id     BIGINT references events,
    requester_id BIGINT references users,
    created      TIMESTAMP without time zone,
    status       VARCHAR
);


