drop table if exists users cascade;
drop table if exists events cascade;
drop table if exists categorys cascade;
drop table if exists requests cascade;
drop table if exists compilations cascade;
drop table if exists compilation_event cascade;

create table if not exists users
(
    id    BIGINT generated by default as identity primary key,
    name  VARCHAR(255) not null unique,
    email VARCHAR(255) not null unique
);

create table if not exists categorys
(
    id   BIGINT generated by default as identity primary key,
    name VARCHAR(255) not null
);

create table if not exists events
(
    id                 BIGINT generated by default as identity primary key,
    title              VARCHAR(120)  not null,
    annotation         VARCHAR(2000) not null,
    category_id        BIGINT references categorys,
    description        VARCHAR(7000) not null,
    event_date         TIMESTAMP,
    location_lat       float4,
    location_lon       float4,
    paid               boolean,
    participant_limit  INTEGER,
    created_on         TIMESTAMP,
    initiator_id       BIGINT references users,
    published_on       TIMESTAMP without time zone,
    request_moderation boolean,
    state              VARCHAR(50),
    views              BIGINT
);



create table if not exists requests
(
    id           BIGINT generated by default as identity primary key,
    event_id     BIGINT references events,
    requester_id BIGINT references users,
    created      TIMESTAMP without time zone,
    status       VARCHAR(50)
);

create table if not exists "compilations"
(
    "id"     BIGINT generated by default as identity primary key,
    "pinned" boolean default false,
    "title"  VARCHAR(120) not null
);

create table if not exists "compilation_event"
(
    "compilation_id" BIGINT references compilations,
    "event_id"       BIGINT references events
);


