drop table if exists stats cascade;

create table if not exists stats
(
    id        BIGINT generated by default as identity primary key not null,
    app       VARCHAR,
    uri       VARCHAR,
    ip        VARCHAR,
    timestamp TIMESTAMP with time zone

);